services:
  postgres:
    image: postgres:15-bullseye
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - pgdata:/usr/local/opt/postgresql@15/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongodata:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
networks:
  app-network:
volumes:
  pgdata:
  mongodata:
