services:
  postgres:
    image: postgres:15-bullseye
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - pgdata:/usr/local/opt/postgresql@15/data
networks:
  app-network:
volumes:
  pgdata:
